// Generated by CoffeeScript 1.4.0
(function() {
  var _;

  _ = require('underscore');

  (function(root) {
    var __;
    __ = {};
    __.yields = function(input) {
      return (_.isFunction(input) ? input() : input);
    };
    if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
      return module.exports = __.yields;
    } else if (root._ != null) {
      return root._.mixin(__);
    } else {
      return root._ = __;
    }
  })(this);

}).call(this);
