// Generated by CoffeeScript 1.4.0
(function() {
  var _;

  _ = require('underscore');

  (function(root) {
    var __;
    __ = {};
    __.concat = function(obj, context) {
      return _.reduce(obj, (function(item, memo) {
        _.each(item, function(subitem) {
          return memo.push(subitem);
        });
        return memo;
      }), [], context);
    };
    if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
      return module.exports = __.concat;
    } else if (root._ != null) {
      return root._.mixin(__);
    } else {
      return root._ = __;
    }
  })(this);

}).call(this);
